# Generated by Django 5.2.8 on 2025-12-23 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='clave_acceso',
            field=models.CharField(blank=True, max_length=49, null=True),
        ),
    ]
