# Generated by Django 5.2.8 on 2026-01-21 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion_app', '0002_factura_clave_acceso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='clave_acceso',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
