# Generated by Django 5.2.8 on 2026-02-19 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_clienteaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='clienteaccount',
            name='debe_cambiar_password',
            field=models.BooleanField(default=True),
        ),
    ]
